name: banner_image
description: A Banner Image widget
version: 1.0.1
homepage: https://github.com/Mto292/banner_image.git


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any





flutter:































